language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_install:
  - sudo apt-get update
  - sudo apt-get install socat
install:
  - pip install behave nose
  - python setup.py install
script:
  - python --version
  - nosetests
  - behave -f progress --junit