""" Setup.py script generated by paver """

from setuptools import setup
from setuptools.command.install import install
from shutil import copy
import os

VERSION = "0.9.8"

INSTALL_REQS = ["pyserial >= 2.5", "pika"]


class CustomInstall(install):  # pylint: disable=W0232
    """Add custom installation after pip install.

    """

    def run(self):
        """Main method

        """
        install.run(self)
#       Custom installation steps here
        folder_path = os.path.join('/opt', 'phase')
        log_folder_path = os.path.join('/var', 'log', 'phase')
        log_conf_path = os.path.join('logs', 'phase-currentcost.conf')
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        if not os.path.exists(log_folder_path):
            os.makedirs(log_folder_path)
        copy(log_conf_path, folder_path)


setup(
    name="phase-currentcost",
    version=VERSION,
    description="Python script to collect data from current cost EnviR",
    long_description=open('README.rst').read(),
    author="Pierre Leray",
    author_email="pierreleray64@gmail.com",
    url="https://github.com/liogen/phase-currentcost",
    license='LICENSE',
    packages=["currentcost"],
    scripts=["bin/phase-currentcost"],
    install_requires=INSTALL_REQS,
    zip_safe=False,
    cmdclass={'install': CustomInstall},
)
